config/routes.rb
Rails.application.routes.draw do

  get 'projects/me', to: 'projects#me'

  resources :projects do
      resources :tasks, except: :index do
        member do
          put 'claim'
          put 'complete'
        end
      end
  end

  resource :dashboard, only: [:show]

  get 'tasks/me', to: 'tasks#me'

  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_many :users, through: :tasks, class_name: "User"

  validates :name, length: { minimum: 2, maximum: 50}
  validates :summary, length: { maximum: 500 }, presence: true
  validates :location, length: { minimum: 2, maximum: 30 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :name, length: { minimum: 2, maximum: 50}
  validates :time_commitment, numericality: true, presence: true
  validates :summary, length: { minimum: 2, maximum: 200 }

  def open!
    self.state = 'opened'
  end

  def claim!
    self.state = 'claimed'
    self.save
  end

  def complete!
    self.state = 'completed'
    self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  has_many :tasks
  has_many :projects, through: :tasks
  has_many :owned_projects, class_name: "Project", foreign_key: "owner_id"


  def timeout_in
      1.hour
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @projects = Project.limit(6)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = Task.where(project_id: params[:id])
    @open = Task.where(project_id: params[:id], state: 'opened')
    @claimed = Task.where(project_id: params[:id], state: 'claimed')
    @completed = Task.where(project_id: params[:id], state: 'completed')
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.owned_projects.build(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def me
    @projects = Project.where(owner_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :summary, :location, :owner_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    dashboard_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, except: :me
  before_action :set_task, only: [:show, :edit, :update, :destroy, :claim, :complete]


  # GET /tasks
  # GET /tasks.json
  # removed because not using
  # def index
  #   @tasks = Task.where(project_id: @project.id)
  # end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.build
    render :layout => nil
  end

  # GET /tasks/1/edit
  def edit
    render :layout => nil
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.build(task_params)
    @task.open!
    respond_to do |format|
      if @task.save
        format.html { redirect_to ([@project, @task]), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: ([@project, @task]) }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to ([@project, @task]), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: ([@project, @task]) }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def claim
    if @task.user_id.blank?
      @task.update_attributes(user_id: current_user.id)
      @task.claim!
    end
    respond_to do |format|
      format.json { render :show, status: :ok, location: ([@project, @task]) }
    end
  end

  def complete
    @task.complete!
    respond_to do |format|
      format.json { render :show, status: :ok, location: ([@project, @task]) }
    end
  end

    # DELETE /tasks/1
    # DELETE /tasks/1.json
    def destroy
      @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def me
    @tasks = Task.where(user_id: current_user.id)
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :time_commitment, :summary, :date_needed, :user_id, :project_id)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboards/show.html.erb
<!-- container adds margins to each side -->
<div class="container-fluid">
      <h1 class="header-dashboard">Below are a few of our active projects. </h1>
      <hr>
  <div class="row no-gutters" id="dashboard-tasks">

    <% @projects.each do |p| %>

    <div class="col-md-3 col-sm-4">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default cust-panel task-panel">
            <div class="panel-heading text-center " id="p-head"><h3><%= link_to p.name, project_path(p) %></h3></div>
            <div class="panel-body" id="p-body"><h5><strong>Project Summary:</strong></h5><br><%= p.summary %></div>
            <div class="panel-footer" id="p-foot"><h5><strong>Project Location:</strong></h5><br><%= p.location %></div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <%= link_to '<button type="button" class="btn btn-default btn-sml buttons">Add a Project</button>'.html_safe, new_project_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdCare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="row">

<!-- nav div -->
  <nav class = "nav navbar-inverse" role = "navigation">
    <div class="container-fluid">
      <% if current_user %>
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
      </div>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "New Project", new_project_path %></li>
          <li><%= link_to "My Projects", projects_me_path %></li>
          <li><%= link_to "My Tasks", tasks_me_path %></li>
          <li><%= link_to "Browse", projects_path %></li>
        </ul>

      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
      <!-- note that styles are coming from the self.scaffolds stylesheed -->
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% else %>

            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </div>
          <% end %>

        </ul>
      </div>
    </nav>


 <%= yield %>

<!-- footer div -->
</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
  <div><h1>Editing Project</h1></div>

  <div><%= render 'form' %></div>

  <div><%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %></div>

app/views/projects/index.html.erb
<body class="projects">


<!-- the notice <p> is not inititially visible -->
<!-- page title header... need to make dynamic or turn this into a header above the nav element -->
<div><h1>Browse Projects</h1></div>
<hr id='headerhr'>

<!-- checks to see if the user on the site is a current user -->
<!-- wrapper div for login sign up section -->
<div>
<% if !current_user %>
  <!-- note that styles are coming from the self.scaffolds stylesheed -->
  <div class='log-in-buttons'>

    <h2>New Users!</h2>

    <button> <%= link_to "Sign Up", new_user_registration_path %> </button>
    <br>
    <h2>Existing Users!</h2>
    <button> <%= link_to "Log In", new_user_session_path %> </button>
  </div>

  <% else %>

 <% @projects.each do |project| %>
<div class="all-projects">

  <ul class="project-list">
    <li><strong>Project</strong></li>
    <li id='project-name'><%= link_to project.name, project_path(project) %></li>
    <li><strong>Summary</strong></li>
    <li><%= project.summary %></li>
    <li><strong>Location</strong></li>
    <li><%= project.location %></li>
  </ul>
  <hr>
  <% end %>
</div>

<!-- closing div for login/sign up container -->

  <br>
  <div>
    <h3>Want to start a new project?</h3>

<%= link_to '<button type="button" class="btn btn-default btn-sml buttons">Create a Project</button>'.html_safe, new_project_path %>

  </div>

  <% end %>

</body>

app/views/projects/me.html.erb
<body class="projects">
  <h1 id='project-header'><strong>My Projects</strong></h1>

  <hr class='my-projects-hr'>

  <% @projects.each do |project| %>

  <div class="project-div">
    <ul class="project-list">
      <li><strong>Project Name</strong></li>
      <li><%= link_to project.name, project_path(project) %></li>
      <li><strong>Summary</strong></li>
      <li><%= project.summary %></li>
      <li><strong>Location</strong></li>
      <li><%= project.location %></li>
      <ul id="edit-delete-button-list">
      <%= link_to '<button type="button" class="btn btn-default btn-sml edit">Edit Project</button>'.html_safe, edit_project_path(project) %>
      <br>
      <%= link_to '<button type="button" class="btn btn-default btn-sml delete">Delete Project</button>'.html_safe, project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
      </ul>
    </ul>
  </div>
  <hr class='after-projects'>

  <% end %>

  <%= link_to '<button type="button" class="btn btn-default btn-sml buttons">Add a Project</button>'.html_safe, new_project_path %>
  <%= link_to '<button type="button" class="btn btn-default btn-sml buttons">Dashboard</button>'.html_safe, dashboard_path %>


</body>

app/views/projects/new.html.erb
<body class="new-project">



  <h1><strong>New Project</strong></h1>
  <hr>

  <%= render 'form' %>
  <hr class="hr-small">

   <%= link_to '<button type="button" id="back-button" class="btn btn-default btn-sml buttons">Back</button>'.html_safe, projects_path %>


</body>

app/views/projects/show.html.erb
<div class="project-page">
  <div class="project-and-tasks">
      <div class="project-info">

        <div class="name">
          <h2><strong>Projects</strong></h2>
          <hr class="top-hr">
          <div id="project-name"><h2><%= @project.name %></h2></div>
        </div>

        <div class="summary">
          <h3>Project Summary</h3>
          <p id="project-summary"><%= @project.summary %></p>
        </div>

        <div class="location">
          <h3>Location</h3>
          <p id="location"><%= @project.location %></p>
        </div>

      </div>

      <hr>

      <div class="available-tasks">
        <h3>Available Tasks</h3>

          <div class="available-tasks-list">
            <% @open.each do |task| %>
              <ul>
                <li><strong><%= task.name %></strong></li>
                <div class="claim-edit-buttons">
                <button class="btn btn-default btn-sml claim" data-id="<%= task.id %>">Claim Task</button>
                <% if current_user.id == @project.owner_id %>

                  <button class="btn btn-default btn-sml edit-task" data-id="<%= task.id %>">Edit Task</button>
                </div>
                <% end %>
              </ul>
            <% end %>
          </div>
        <% if current_user.id == @project.owner_id %>
          <button class='btn btn-default btn-sml new-task-button'>Add Task</button>

        <% end %>

      </div>

      <div class="space"></div>

      <hr>

      <div class="tasks-in-progress">
        <h3>Claimed Tasks</h3>
          <div class="claimed-tasks-list">
            <% @claimed.each do |task| %>
              <ul>

                <li><strong><%= task.name %></strong></li>

                <% if current_user.id == @project.owner_id %>

                  <button class="btn btn-default btn-sml edit-task" data-id="<%= task.id %>">Edit Task</button>
                <% end %>
              </ul>

            <% end %>
          </div>
      </div>


      <hr>

      <div class="completed-tasks">
        <h3>Completed Tasks</h3>

          <% @completed.each do |task| %>
            <ul>
              <% if task.state == 'completed'%>
              <li><strong><%= task.name %></strong></li>
              <% end %>
            </ul>
          <% end %>
      </div>

      <div class="space"></div>
    </div>

  <div id="new-task"></div>
  <div id="edit-form"></div>

</div>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task],:remote => true, :html => {:'data-type' => 'json'})do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :time_commitment %><br>
    <%= f.number_field :time_commitment %>
  </div>

  <div class="field">
    <%= f.label :date_needed %><br>
    <%= f.datetime_select :date_needed , :ampm => true, :minute_step => 15%>
  </div>
  <div class="actions" id="submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div><p id="notice"><%= notice %></p></div>

<div>
  <div><h1>Listing Tasks</h1></div>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Time commitment</th>
          <th>Status</th>
          <th>Date needed</th>
          <th>User</th>
          <th>Project</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= task.name %></td>
            <td><%= task.time_commitment %></td>
            <td><%= task.state %></td>
            <td><%= task.date_needed %></td>
            <td><%= task.user_id %></td>
            <td><%= task.project_id %></td>
            <td><%= link_to 'Show', project_task_path(@project, task) %></td>
            <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
            <td><%= link_to 'Destroy', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
<br>

  <div><%= link_to 'New Task', new_project_task_path %></div>

app/views/tasks/me.html.erb
<body class="tasks-me-page">

<h1 id='task-header'><strong>My Tasks</strong></h1>
<hr>
<% @tasks.each do |task| %>

<div class="task-div">
  <ul class="task-list">
    <li><strong><%= task.project.name %></strong></li>
    <li>  <p class="task-name <%=task.state == 'completed' ? 'strike' : ""  %>" id='<%= task.id %>'><%= task.name %></p></li>
    <li><button  type="button" class="btn btn-default btn-sml complete" data-id='<%= task.id %>' data-projectid='<%= task.project_id %>' >Mark as Complete!</button></li>
  </ul>
</div>
<hr class='after-task'>

<% end %>


<div id="bottom-buttons">
<%= link_to '<button type="button" class="btn btn-default btn-sml buttons">Browse Projects</button>'.html_safe, projects_path %>
<%= link_to '<button type="button" class="btn btn-default btn-sml buttons">Dashboard</button>'.html_safe, dashboard_path %>
</div>
</body>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>
<hr>

<%= link_to '<button type="button" id="back-button" class="btn btn-default btn-sml buttons">Back</button>'.html_safe, project_path(@project) %>

app/views/tasks/show.html.erb
<div><p id="notice"><%= notice %></p></div>

<div>
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Time commitment:</strong>
  <%= @task.time_commitment %>
</p>

<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>

<p>
  <strong>Date needed:</strong>
  <%= @task.date_needed %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>
<div>
  <%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
  <%= link_to 'Back', project_tasks_path %>
</div>
</div>

app/views/welcome/index.html.erb
  <div class="hero container-fluid">


      <div class="logo"><svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 729.35 178.27"><defs><style>.cls-1{font-size:136px;fill:#fff;font-family:Bebas Neue;letter-spacing:12.63px;}</style></defs><title>crowdcare-logo</title><text class="cls-1" transform="translate(0 147.26) scale(0.95 1.05)">crowdcare</text></svg></div>

      <%= link_to '<button type="button" class="btn btn-default btn-lg get-started">Get Started</button>'.html_safe, new_user_registration_path %>

  </div>



</div>